default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: <%= GhrConfig::PUMA::JOB_THREADS %>
      processes: <%= GhrConfig::PUMA::JOB_CONCURRENCY %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
