name: Docker Image CI

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u flori303 -p ${{ secrets.DOCKER_BUILDER_TOKEN }}
        if [[ "$GITHUB_REF_NAME" = "master" ]]
        then
          make push
        else
          make build
        fi
